name: Build and Push

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"

      - name: Increment Version
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          MAJOR=$(echo $VERSION | cut -d. -f1)
          MINOR=$(echo $VERSION | cut -d. -f2)
          PATCH=$(echo $VERSION | cut -d. -f3)

          # Increment the project version
          if [ $PATCH -eq 9 ]; then
            PATCH=0
            if [ $MINOR -eq 9 ]; then
              MINOR=0
              MAJOR=$((MAJOR+1))
            else
              MINOR=$((MINOR+1))
            fi
          else
            PATCH=$((PATCH+1))
          fi

          NEW_VERSION="$MAJOR.$MINOR.$PATCH"

          mvn versions:set -DnewVersion=$NEW_VERSION
          git config --local user.email "GitHub Actions"
          git config --local user.name "GitHub Actions"
          git commit -am "Increment version to $NEW_VERSION"
          git push

      - name: Build and Push Docker Image
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          docker build -t myapp:$VERSION .
          echo $DOCKER_HUB_ACCESS_TOKEN | docker login -u $DOCKER_HUB_USERNAME --password-stdin
          docker tag myapp:$VERSION $DOCKER_HUB_USERNAME/myapp:$VERSION
          docker push $DOCKER_HUB_USERNAME/myapp:$VERSION
