name: Build and Push

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev
    outputs:
      new_version: ${{ steps.versioning.outputs.new_version }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"

      - name: Increment Version
        run: |
          cd myapp
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          MAJOR=$(echo $VERSION | cut -d. -f1)
          MINOR=$(echo $VERSION | cut -d. -f2)
          PATCH=$(echo $VERSION | cut -d. -f3)

          # Increment the project version
          if [ $PATCH -eq 9 ]; then
            PATCH=0
            if [ $MINOR -eq 9 ]; then
              MINOR=0
              MAJOR=$((MAJOR+1))
            else
              MINOR=$((MINOR+1))
            fi
          else
            PATCH=$((PATCH+1))
          fi

          NEW_VERSION="$MAJOR.$MINOR.$PATCH"

          mvn versions:set -DnewVersion=$NEW_VERSION
          git config --local user.email "GitHub Actions"
          git config --local user.name "GitHub Actions"
          git commit -am "Increment version to $NEW_VERSION"
          git push
          echo "::set-output name=new_version::$NEW_VERSION"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and Push Docker Image
        env:
          NEW_VERSION: ${{ needs.build.outputs.new_version }}
        run: |
          echo !!!!!!!!!!!!!!!!!!!!!!-$NEW_VERSION
          docker build -t myapp:$NEW_VERSION .
          docker tag myapp:$NEW_VERSION $DOCKER_HUB_USERNAME/myapp:$NEW_VERSION
          docker push $DOCKER_HUB_USERNAME/myapp:$NEW_VERSION
