name: Build and Push

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"

      - name: Increment Version
        id: versioning
        run: |
          cd myapp
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          MAJOR=$(echo $VERSION | cut -d. -f1)
          MINOR=$(echo $VERSION | cut -d. -f2)
          PATCH=$(echo $VERSION | cut -d. -f3)

          if [ $PATCH -eq 9 ]; then
            PATCH=0
            if [ $MINOR -eq 9 ]; then
              MINOR=0
              MAJOR=$((MAJOR+1))
            else
              MINOR=$((MINOR+1))
            fi
          else
            PATCH=$((PATCH+1))
          fi

          NEW_VERSION="$MAJOR.$MINOR.$PATCH"
          mvn versions:set -DnewVersion=$NEW_VERSION

          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add pom.xml
          git commit -am "Increment version to $NEW_VERSION"
          git push

          echo "::set-output name=new_version::$NEW_VERSION"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          echo "Version: ${{ steps.versioning.outputs.new_version }}"
          docker build -t myapp:${{ steps.versioning.outputs.new_version }} .
          docker tag myapp:${{ steps.versioning.outputs.new_version }} $DOCKER_HUB_USERNAME/myapp:${{ steps.versioning.outputs.new_version }}
          docker push $DOCKER_HUB_USERNAME/myapp:${{ steps.versioning.outputs.new_version }}
